### ISSUE TITLE
Release 1.0

### ISSUE THREAD

**Issue by crookse** [drashland/deno-drash#158]
Release Date: May 13, 2020
Code freeze: May 1, 2020

- [ ] E2E test app_test.ts
    - This will need to implement multiple resources that cover most (if not all) the entire [Drash Lifecycle](https://drash.land/docs/#/lifecycle-diagram)
- [x] ~Update the [Drash Lifecycle Diagram](https://drash.land/docs/#/lifecycle-diagram)~
- [x] #173 Use the `Accept` header
    - [x] Implementation
    - [x] Documentation
- [x] #175 `import { Drash }` instead of `import Drash`
    - [x] Implementation
    - [x] Documentation
- [x] #183 Support HTTPS
    - [x] Implementation
    - [x] Documentation
- [x] #186 resource-level middleware decorators
    - [x] Implementation
    - [x] Documentation
- [x] #200 server-level middleware standardization
    - [x] Implementation
    - [x] Documentation
- [x] #197 expose `Drash.version`
    - [x] Implementation
    - [x] Documentation (just rebuild API Reference)
- [x] #196 expose `Drash.Http.Server.port`
    - [x] Implementation
    - [x] Documentation (just rebuild API Reference)
- [x] #199 `await server.run()`
    - [x] Implementation
    - [x] Documentation
