### ISSUE TITLE
Add .getAll*() method on request object

### ISSUE THREAD

**Issue by besingamkb** [drashland/deno-drash#382]
## Summary
https://drash.land/drash/#/tutorials/requests/handling-url-query-params
What: Nice to have a `.all()` methods or similar on the `this.request` for handling all query params.

Why: easier to handle a lot of  parameters so you can assign it on a variable..
```ts
const params = this.request.all();
params['id'];
params['name'];
params['email'];
...
```

## Acceptance Criteria
Edit by @ebebbington below:

- [x] (#396) A `getAllUrlQueryParams()` method on `Drash.Http.Request` that returns `{[key: string]: string|null} | null`
    - If no params passed in, return null, 
- [x] (#404) `getAllBodyParams()`, `getAllHeaderParams()`, `getAllPathParams()`
- [x] Tests
- [x] Documentation (https://github.com/drashland/website/issues/211) (to be handled by Drash Land maintainers)

**Comment by ebebbington** [comment]
I agree with this, nice one @besingamkb, i've just edited the issue description to include tests for acceptance criteria

**Comment by MVEMCJSUNPE** [comment]
Can I work on the tests?

**Comment by ebebbington** [comment]
Hey @MVEMCJSUNPE, to work on the tests you'll need to implement the feature - feel free to take this issue on :)

**Comment by MVEMCJSUNPE** [comment]
@ebebbington I'll take this issue on then; looking at getUrlQueryParam, I don't think I'll have too much trouble with writing getAllUrlQueryParams.

**Comment by ebebbington** [comment]
@besingamkb Can we have some confirmation on what you liked to see? Because the title and description feels very confusion, what would you like to see:
```typescript
const all = this.request.all()
console.log(all) // { headers: ..., queryParams: ..., etc etc }
// or
const queryParams = this.request.getAllQueryParams()
const queryStrings = this.request.getAllQueryStrings()
// etc etc
```

**Comment by besingamkb** [comment]
@ebebbington i think that will work as long as we get all the data from any kind of request verb. the main point of this feature request is to make it easier for devs to access data. so instead of doing it one by one with `this.request.getBodyParam('test1')` we can do it this way.

```ts
const queryParams = this.request.getAllQueryParams();
queryParams['test1']
queryParams['test2']
// etc etc
```

**Comment by crookse** [comment]
would the following suffice?

```typescript
// Get EVERYTHING
request.all() // => { query_parms: { ... }, header_params: { ... }, body_params: { ... } }

// Only get query params
request.getAllQueryParams(); // { some_param: ..., another_param: ... }

// Only get header params
request.getAllHeaderParams(); // { some_param: ..., another_param: ... }

// Only get body params
request.getAllBodyParams(); // { some_param: ..., another_param: ... }
```

**Comment by besingamkb** [comment]
@crookse this is what exactly I was looking

**Comment by ebebbington** [comment]
@besingamkb `.all()` and `getAllUrlQueryParams()` are completely different, and in https://github.com/drashland/deno-drash/issues/382#issuecomment-716287118 you only mentioned getting all url query. params, but i think it's safe to say that this feature request is to add all defined in https://github.com/drashland/deno-drash/issues/382#issuecomment-716294626

**Comment by besingamkb** [comment]
ohh. my bad i really didn't notice you have  `.all()` on this comment https://github.com/drashland/deno-drash/issues/382#issuecomment-716215836

**Comment by ebebbington** [comment]
`getAllUrlQueryParams` was added in https://github.com/drashland/deno-drash/pull/396, by @MVEMCJSUNPE
