### ISSUE TITLE
[cli] Drash CLI

### ISSUE THREAD

**Issue by ebebbington** [drashland/deno-drash#395]
## Summary

What: A Drash CLI that users can use via `drash` command.

Why: It'd be nice to have a `drash` command that handles:
- Creating files
- Serving the application
- ~Testing the application~ (don't do... people should be free to use their own test CLIs)

## Acceptance Criteria

- [ ] #438 Migrate create_app.ts to be in the CLI (this should also cover `drash make app app-name` subcommand)
- [ ] #442 `drash serve` subcommand
- [ ] #443 `drash make resource` subcommand

## Examples

```
drash serve

INFO Your Drash application has started at http://localhost:1447
```

```
drash make:resource /path/to/my_resource.ts

INFO Your resource "MyResource" has been created at /path/to/my_resource.ts
```

**Comment by saragee3** [comment]
should `create_app` script be a part of this main cli?

**Comment by ebebbington** [comment]
Think so yeah, I believe that would be one of the commands?

**Comment by crookse** [comment]
spoke to sara, `test` subcommand doesn't make sense. if people want to add tests to drash, they can use the `rhum` cli.

**Comment by crookse** [comment]
@saragee3, when you start making the `create_app` stuff, bind it to a `make:app` subcommand

**Comment by ebebbington** [comment]
👍

**Comment by crookse** [comment]
@saragee3,

could you try to accomplish the following instead of what's in the description?

```
drash make app app-name
drash make resource /file/to/create.ts
drash serve --hostname= --port=
```

**Comment by crookse** [comment]
@saragee3,

i updated the description and broke out this issue into separate issues

**Comment by Japroz-Saini** [comment]
I can make the CLI

**Comment by crookse** [comment]
moving this to semester 2

**Comment by japrozs** [comment]
You can make the command line interface using `commander`

**Comment by crookse** [comment]
@japrozs, two issues with that:

1. it's a node package and drash is deno only
2. it creates a 3rd party dependency that we have no control over

ultimately, the drash cli is going to use Line

**Comment by japrozs** [comment]
@crookse , the commander npm is a single file. I can easily convert it to typescript for deno to use and then u guys can use that as your own command line engine

**Comment by japrozs** [comment]
Commander code file : https://www.github.com/tj/commander.js/tree/master/index.js

The only problem is that you wil have to implement the functions such as reading command line arguments and executing shell commands because this file uses nodejs standard modules which are not present in deno

**Comment by crookse** [comment]
we have a cli framework already and plan to use it. it's already written, tested, has tutorials, so switching over to a commander-like framework or any other framework is already out of the question

**Comment by ebebbington** [comment]
closing as the drash CLI is no longer implemented for v2, we will be going with a template repo instead
