### ISSUE TITLE
[Code Removal] Drash.Compilers.TemplateEngine (Removal Date: 01-01-2021)

### ISSUE THREAD

**Issue by crookse** [drashland/deno-drash#430]
## Summary

See #399 and #424 for discussions surrounding deprecation and removal of this code.

_Note to team: November 6, 2020 is a tentative date. If we happen to finish the tasks later than November 6, 2020, that's fine._

## Tasks

- [x] November 6, 2020: Merge #428 (after_resource hook)
- [x] November 6, 2020: Merge #424 (deprecate Drash.Compilers.TemplateEngine)
- [x] November 6, 2020: Merge drashland/deno-drash-middleware#62 (Tengine - A template engine middleware)
- [x] November 6, 2020: Release deno-drash-middleware v0.6.0
- [x] November 6, 2020: Release deno-drash v1.3.0
- [x] January 1, 2021: Open PR to remove Drash.Compilers.TemplateEngine and all related tests
- [ ] January 1, 2021: Merge the above PR
- [ ] January 1, 2021: Release deno-drash minor version
